<a href="https://colab.research.google.com/github/jessamcs/Week-5-Machine-Learning/blob/main/Week5_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#PRE PROCESSING EXERCISE FOR WEEK 5 - SARCAUGA
#IMPORTS MACHINE LEARNING
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_selector
from sklearn.impute import SimpleImputer

#Read the path
path = '/content/Raw_Medical_Data_for_day1.csv'
df = pd.read_csv(path)
df.head()

   Unnamed: 0 State       Lat  ...  Initial_days  TotalCharge  Additional_charges
0           1    AL  34.34960  ...     10.585770  3726.702860        17939.403420
1           2    FL  30.84513  ...     15.129562  4193.190458        17612.998120
2           3    SD  43.54321  ...      4.772177  2434.234222        17505.192460
3           4    MN  43.89744  ...      1.714879  2127.830423        12993.437350
4           5    VA  37.59894  ...      1.254807  2113.073274         3716.525786

[5 rows x 33 columns]

In [3]:
# Train test split the data to prepare for machine learning

X = df.drop(columns = ['Unnamed: 0', 'Additional_charges'])
y = df['Additional_charges']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

#make categorical and numeric selectors
cat_selector = make_column_selector(dtype_include='object')

#select categorical columns
cat_data = X_train[cat_selector(X_train)]
cat_data

    State      Area  ... Complication_risk     Services
82     TN     Urban  ...            Medium  Intravenous
991    AL     Urban  ...            Medium   Blood Work
789    TN     Urban  ...              High  Intravenous
894    SD     Rural  ...              High   Blood Work
398    MI  Suburban  ...            Medium   Blood Work
..    ...       ...  ...               ...          ...
106    NY  Suburban  ...            Medium  Intravenous
270    IN  Suburban  ...              High   Blood Work
860    OH     Urban  ...            Medium   Blood Work
435    CA  Suburban  ...            Medium   Blood Work
102    NY     Rural  ...            Medium   Blood Work

[750 rows x 7 columns]

In [ ]:
#Identify each feature as numerical, ordinal, or nominal. 
#//(Please provide this answer in a text cell in your Colab notebook)

#NUMERICAL FEATURE - are given attributes to like for example height or weight
# // the objective is to determine numerical values - Age, BMI

#NOMINAL -  made of discrete values with no numerical relationship between the different categories 
# // like for example, sex, skin color etc

# ORDINAL FEATURES -discrete integers that can be ranked or sorted
# // In this exercise for example , Children

In [4]:
# One Hot Encode the nominal features
from sklearn.compose import make_column_selector
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [5]:
region_selector = make_column_selector(dtype_include='object')
region_data = X_train[region_selector(X_train)]
region_data
ohe_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_encoder.fit(region_data)
region_ohe = ohe_encoder.transform(region_data)
region_ohe
pd.DataFrame(region_ohe, columns=ohe_encoder.get_feature_names(region_data.columns))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

     State_AK  State_AL  ...  Services_Intravenous  Services_MRI
0         0.0       0.0  ...                   1.0           0.0
1         0.0       1.0  ...                   0.0           0.0
2         0.0       0.0  ...                   1.0           0.0
3         0.0       0.0  ...                   0.0           0.0
4         0.0       0.0  ...                   0.0           0.0
..        ...       ...  ...                   ...           ...
745       0.0       0.0  ...                   1.0           0.0
746       0.0       0.0  ...                   0.0           0.0
747       0.0       0.0  ...                   0.0           0.0
748       0.0       0.0  ...                   0.0           0.0
749       0.0       0.0  ...                   0.0           0.0

[750 rows x 76 columns]